In [4]:
import numpy as np

In [5]:
d1 = [['x1', 'x2', 'x3'], 'c1']
d2 = [['x1', 'x2', 'x4'], 'c1']
d3 = [['x4', 'x5', 'x6'], 'c2']

d4 = [['x1', 'x4', 'x5']]

In [21]:
p_c = [2.0 / 3, 1.0 / 3]
cnt_x_c = np.array([[2, 2, 1, 1, 0, 0], [0, 0, 0, 1, 1, 1]])
p_x_c = np.divide(cnt_x_c.astype(float) + 1, np.array([[6],[3]]) + 6)

In [22]:
print p_x_c

[[ 0.25        0.25        0.16666667  0.16666667  0.08333333  0.08333333]
 [ 0.11111111  0.11111111  0.11111111  0.22222222  0.22222222  0.22222222]]


In [23]:
p_x_c_d4 = np.prod(p_x_c[:,3:], axis=1)
np.multiply(p_x_c_d4, p_c)

array([ 0.0007716 ,  0.00365798])

Вероятность первого класса: 0.0007716 
<p>
Вероятность второго класса: 0.00365798